#!/usr/bin/env bash

set -eu
set -x

definition=$1; shift

basename=$1; shift
pattern_file=$basename.input
transcript=$basename.transcript
kore_output=$basename.kore

kore-exec --module BOOGIE "$definition/boogie-kompiled/definition.kore" \
          --pattern "$pattern_file" \
          --search ./frontend/search-pattern.kore --searchType FINAL \
          --output "$kore_output" --solver-transcript "$transcript" \
          "$@"
# kprint $definition/boogie-kompiled $kore_output
./.build/defn/frontend/frontend-kompiled/parser_Pattern_KORE-SYNTAX "$kore_output"
