language: java
services:
  docker
git:
  depth: 3
jobs:
  include:
    - stage: Build Docker Image
      script: "travis_wait 10 docker build --build-arg K_COMMIT=$(cd ext/k && git rev-parse --short=7 HEAD) --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --tag boogie-semantics ."
    - stage: Create Docker Container
      script: "docker create --name boogie boogie"
    - stage: Build semantics
      script:
      - "travis_wait 10 docker run boogie-semantics --tty --name boogie ./build boogie"
    - stage: Test
      script:
      - "travis_wait 10 docker run boogie-semantics --tty  --name boogie ./build"
