#!/usr/bin/env python3
# Usage: $0 <k-output> <boogie-output> 

import sys
import difflib
import re

def lines(file):
    file = open(file)
    ret = file.readlines()
    file.close()
    return ret
    
def filter_k_failure_messages(line):
    match = re.search(r'#failure \( "([^"]*)"', line)
    if match: return match.group(1) + '\n'
k_output_file = sys.argv[1]
k_output = list(filter(None, map(filter_k_failure_messages, lines(k_output_file))))

def filter_boogie_failure_messages(line):
    match = re.search(r'([^\(]*)\((\d*),(\d*)\): (Error.*$)', line)
    if not match: return
    file = match.group(1)
    line = match.group(2)
    column = match.group(3)
    message = match.group(4)
    return file + '(' + line + '): ' + message + '\n'
 
boogie_output_file = sys.argv[2]
boogie_output = list(filter(None, map(filter_boogie_failure_messages, lines(boogie_output_file))))

sys.stdout.writelines(difflib.unified_diff(k_output, boogie_output))
