#!/usr/bin/env bash

set -eu
basedir=$(cd $(dirname $0); cd ..; pwd)
PATH="$basedir/ext/k/k-distribution/target/release/k/bin/:$PATH"

definition=$1; shift
program=$1; shift

mkdir -p "$(pwd)/.build/tmp/"
working_dir=$(mktemp -d $(pwd)/.build/tmp/boogie-driver-XXXXXX)

krun --directory "$definition" --output kore $program > "$working_dir/initconfig"
krun --directory $basedir/.build/defn/driver/ "$working_dir/initconfig" -cWorkingDir=\"$working_dir\" "$@"
